apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpipam.fullname" . }}
  labels:
    {{- include "phpipam.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "phpipam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "phpipam.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "phpipam.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: IPAM_DATABASE_HOST
              value: {{ .Values.database.hostname | quote }}
            - name: IPAM_DATABASE_USER
              value: {{ .Values.database.username | quote }}
            - name: IPAM_DATABASE_PASS
              value: {{ .Values.database.password| quote }}
            - name: IPAM_DATABASE_NAME
              value: {{ .Values.database.database | quote }}
            - name: IPAM_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phpipam.fullname" . }}-cron
  labels:
    {{- include "phpipam.labels" . | nindent 4 }}
spec:
  replicas: 1 # maximum 1 is allowed
  selector:
    matchLabels:
      {{- include "phpipamCron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "phpipamCron.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "phpipam.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.phpipamCron.image.repository }}:{{ .Values.phpipamCron.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ with .Values.phpipamCron.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: IPAM_DATABASE_HOST
              value: {{ .Values.database.hostname | quote }}
            - name: IPAM_DATABASE_USER
              value: {{ .Values.database.username | quote }}
            - name: IPAM_DATABASE_PASS
              value: {{ .Values.database.password| quote }}
            - name: IPAM_DATABASE_NAME
              value: {{ .Values.database.database | quote }}
            - name: IPAM_DATABASE_PORT
              value: {{ .Values.database.port | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
